name: medium
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.3.1
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.2
  - aiosignal=1.4.0
  - alsa-lib=1.2.14
  - asttokens=3.0.1
  - astunparse=1.6.3
  - attrs=25.4.0
  - black=25.1.0
  - bleach=6.3.0
  - blinker=1.9.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=6.2.2
  - cairo=1.18.0
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.3.1
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - cryptography=46.0.3
  - cycler=0.12.1
  - dbus=1.13.6
  - debugpy=1.8.17
  - decorator=5.2.1
  - double-conversion=3.3.1
  - executing=2.2.1
  - expat=2.7.3
  - flatbuffers=23.5.26
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - freetype=2.14.1
  - frozenlist=1.7.0
  - gast=0.6.0
  - giflib=5.2.2
  - google-auth=2.43.0
  - google-auth-oauthlib=1.2.2
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - grpcio=1.59.3
  - h2=4.3.0
  - h5py=3.15.1
  - harfbuzz=9.0.0
  - hdf5=1.14.6
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.11
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - joblib=1.5.2
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - kaggle=1.8.0
  - kagglesdk=0.1.13
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.4
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libclang-cpp18.1=18.1.8
  - libclang13=21.1.0
  - libcups=2.3.3
  - libcurl=8.17.0
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.80.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libgrpc=1.59.3
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - libllvm18=18.1.8
  - libllvm21=21.1.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.51
  - libpq=16.11
  - libprotobuf=4.24.4
  - libre2-11=2023.09.01
  - libsodium=1.0.20
  - libsqlite=3.51.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=2.41.2
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.11.0
  - libxml2=2.13.9
  - libxslt=1.1.43
  - libzlib=1.3.1
  - markdown=3.10
  - markupsafe=3.0.3
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - multidict=6.6.3
  - munkres=1.1.4
  - mypy=1.18.2
  - mypy_extensions=1.1.0
  - mysql-common=8.3.0
  - mysql-libs=8.3.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - oauthlib=3.3.1
  - openjpeg=2.5.4
  - openssl=3.6.0
  - opt_einsum=3.4.0
  - parso=0.8.5
  - pathspec=0.12.1
  - pcre2=10.43
  - pexpect=4.9.0
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - propcache=0.3.1
  - psutil=7.1.3
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pycparser=2.22
  - pygments=2.19.2
  - pyjwt=2.10.1
  - pyopenssl=25.3.0
  - pyparsing=3.2.5
  - pyside6=6.7.2
  - pysocks=1.7.1
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-flatbuffers=25.9.23
  - python-slugify=8.0.4
  - python_abi=3.11
  - pyu2f=0.1.5
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt6-main=6.7.2
  - re2=2023.09.01
  - readline=8.2
  - requests=2.32.5
  - requests-oauthlib=2.0.0
  - rsa=4.9.1
  - scikit-learn=1.7.2
  - scipy=1.16.3
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.1.10
  - stack_data=0.6.3
  - tensorboard-data-server=0.7.0
  - tensorflow-estimator=2.15.0
  - termcolor=3.2.0
  - text-unidecode=1.3
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - types-requests=2.32.4.20250913
  - types-tqdm=4.67.0.20250809
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - unicodedata2=17.0.0
  - urllib3=2.5.0
  - wayland=1.24.0
  - wcwidth=0.2.14
  - webencodings=0.5.1
  - werkzeug=3.1.3
  - wheel=0.45.1
  - wrapt=1.14.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.6
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yarl=1.22.0
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - aiofiles==25.1.0
      - chex==0.1.90
      - dotenv==0.9.9
      - etils==1.13.0
      - flax==0.10.4
      - fsspec==2025.10.0
      - humanize==4.14.0
      - importlib-resources==6.5.2
      - jax==0.8.1
      - jaxlib==0.8.1
      - keras==3.12.0
      - libclang==18.1.1
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - msgpack==1.1.2
      - namex==0.1.0
      - numpy==2.1.3
      - optax==0.2.5
      - optree==0.18.0
      - orbax-checkpoint==0.11.30
      - packaging==23.2
      - pandas==2.3.3
      - protobuf==5.29.5
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - rich==14.2.0
      - simplejson==3.20.2
      - tensorboard==2.19.0
      - tensorflow==2.19.0
      - tensorflow-decision-forests==1.12.0
      - tensorflow-hub==0.16.1
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflowjs==4.22.0
      - tensorstore==0.1.79
      - tf-keras==2.19.0
      - toolz==1.1.0
      - treescope==0.1.10
      - tzdata==2025.2
      - wurlitzer==3.1.1
      - ydf==0.13.0
prefix: /home/lcc_rn_08/.conda/envs/medium
